# Generated by Django 4.2.10 on 2025-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='imaging_studies/'),
        ),
    ]
