# Generated by Django 4.2.10 on 2025-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='access_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='access_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
